[versions]
kotlin = "2.4.0"
kotlinx-io = "0.9.1"
kim = "0.32.0"

[libraries]
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kim = { group = "de.stefan-oltmann", name = "kim", version.ref = "kim" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
