[versions]
junit = "4.13.2"
kotlin = "2.2.0"
kotlinx-io = "0.8.0"
ashampoo-kim = "0.26"

[libraries]
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
ashampoo-kim = { group = "com.ashampoo", name = "kim", version.ref = "ashampoo-kim" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
